### ISSUE TITLE
(suggestion) swap receiving links for quick vids

### ISSUE THREAD

**Issue by garandal245** [quickvids/replugged-plugin#1]
as said above.

If message is received with tiktok/instagram reels link replace the message with the quickvids equivalent or add a right click menu option to open quickvids equivalent (so it doesnt spam the api and the user has to choose to embed the video instead of auto doing so)

**Comment by Wolfhound905** [comment]
Hello, I no longer recommend the use of this plugin due to Discord adding User Apps. Please add the the bot to your account for use of the /tiktok command here: [User Invite](https://api.quickvids.app/v2/discord/login?invite=true&user_install=true)
