### ISSUE TITLE
[Bug] double messages

### ISSUE THREAD

**Issue by rakosi2** [quickvids/replugged-plugin#2]
When this plugin is installed/enabled. All messages that I send will be sent twice. When I disable/uninstall this plugin, discord stops double sending. I am on Windows 11 if that is helpful.

**Comment by Wolfhound905** [comment]
Hello, sorry for the late reply, I meant to respond. It slipped past me.

Could you please tell me what other plugins you have installed?

**Comment by Wolfhound905** [comment]
Hello, I no longer recommend the use of this plugin due to Discord adding User Apps. Please add the the bot to your account for use of the /tiktok command here: [User Invite](https://api.quickvids.app/v2/discord/login?invite=true&user_install=true)
