### ISSUE TITLE
The plugin doesn't work (canary)

### ISSUE THREAD

**Issue by lisekilis** [quickvids/replugged-plugin#4]
I get this error every time I try to use it
![image](https://github.com/quickvids/replugged-plugin/assets/101191226/db673e17-543c-49a4-b8e6-2ef18393e576)
...
![image](https://github.com/quickvids/replugged-plugin/assets/101191226/e25a741e-8ebe-497f-806f-6ec8021d918a)
Tried debugging it by doing various stuff such as: reinstalling, removing all other plugins, trying on a fresh replugged install and a fresh windows install... nothing worked
My bet is on [this](https://github.com/quickvids/replugged-plugin/blob/fa88fb7a1cdc3d76993009a1f2b1d9f1113556f3/src/index.ts#L8) api call returning something wrong or nothing at all
Update: Here's the Error: 
![image](https://github.com/quickvids/replugged-plugin/assets/101191226/9e852755-c199-4198-9dc0-753c61864366)
... my assumptions were correct. The Api call returns an error because of the lack of permission

**Comment by Wolfhound905** [comment]
Canary.discord.com is not included in the CORS list. I will add it. Additionally, I do not recommend using the canary version of Discord, as it offers no advantages, and they rarely test anything on it anymore.

**Comment by lisekilis** [comment]
I started using canary a long time ago when powercord required it and I just stuck with it
Gotta love my pisscord™
![image](https://github.com/quickvids/replugged-plugin/assets/101191226/714dcaa8-4250-4408-a88d-ac6a8898f83e)

**Comment by lisekilis** [comment]
So uhhh
you gonna fix it?
![image](https://github.com/quickvids/replugged-plugin/assets/101191226/ff75f494-6998-4fc1-9831-56b91569893e)

**Comment by Wolfhound905** [comment]
Hello, I no longer recommend the use of this plugin due to Discord adding User Apps. Please add the the bot to your account for use of the /tiktok command here: [User Invite](https://api.quickvids.app/v2/discord/login?invite=true&user_install=true)
