### ISSUE TITLE
[Bug] Compatibility issue with RepluggedPGP and Translator

### ISSUE THREAD

**Issue by Czekoloczek** [quickvids/replugged-plugin#5]
Having enabled:
- [RepluggedPGP](https://github.com/SammCheese/RepluggedPGP)
- [QuickVids Embeds](https://github.com/quickvids/replugged-plugin)
- [Translator](https://github.com/Socketlike/replugged-plugins)

causes the message to be sent three times
(if you have only 2 enabled, for example, QuickVids and Translator the message will be sent two times)

(The same bug as in #2)

**Comment by Czekoloczek** [comment]
- https://github.com/SammCheese/RepluggedPGP/issues/6
- https://github.com/Socketlike/replugged-plugins/issues/4

**Comment by Wolfhound905** [comment]
Hello, I no longer recommend the use of this plugin due to Discord adding User Apps. Please add the the bot to your account for use of the /tiktok command here: [User Invite](https://api.quickvids.app/v2/discord/login?invite=true&user_install=true)
